title: Alexander Oloo
author: alekcz
email: your-email@domain.com
bio:  Engineer. Designer. Jack of all trades. Great at Product, Clojure, coaching and debugging.
description: > # this means to ignore newlines until "current:"
  I solve business problems using design and code. I build APIs, craft user experiences, and mentor designers & devs. My toolbox consists of Coaching, Clojure, Javascript, Vue, Angular, CSS, Product Design, UX, and UI.  
current: >  
  I'm currently a Design Director at the Absa Design Office where I work with a bunch of awesome humans. My primary focus is the design, analysis, and optimization of apps on the web.
previous: >    
  I had the privilege of lecturing at the University of Pretoria for 4 years, writing code at SAP for 3 years, and building NeedTyres.
outro: >   
  Oh yes...and I code a lot. Wanna chat? Hit me up on twitter.
show_excerpts: true # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass
plainwhite:
  name: Alexander Oloo
  tagline: Developer. Designer
  date_format: "%b %-d, %Y"
  sitemap: true # set to true to generate sitemap.xml content

  # generate social links in footer
  social_links:
    twitter: alekcz
    github:  alekcz
    linkedIn: in/alekcz
    rss: rss
    # dribbble: jekyll
    # facebook: jekyll
    # flickr:   jekyll
    # instagram: jekyll
    # linkedin: jekyll
    # pinterest: jekyll
    # youtube: jekyll
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: CloudCannon
    # telegram: jekyll
    # googleplus: +jekyll
    # microdotblog: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
theme: plainwhite

plugins_dir:
  - jekyll-seo-tag
#  - jekyll-feed